# Continious Integration Check Workflow
name: CI Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  linter:
    name: Linter Checks
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Check Home Assistant Add-on
      uses: frenck/action-addon-linter@main
      with:
        path: "./home-assistant-addon"

    - name: Check Home Assistant Add-on (strict)
      uses: frenck/action-addon-linter@main
      with:
        path: "./home-assistant-addon-strict"
